### ISSUE TITLE
HAPI2.0 サーバ側実装 TODO

### ISSUE THREAD

**Issue by ashie** [project-hatohol/hatohol#1219]
どこで共有するか迷うところだが、ひとまず手元のメモをissueにあげておく。
以下、現状で気がついているTODO

* [x] サーバ起点のexchangeProfile
* [x] exchangeProfileが完了するまで他のprocedureの返信抑制
* [x] updateおよびput系procedureのIDを適切なID(responseのID)をセット (must)
* [x] exchengeProfileでプロセス名セット (must)
* [x] exchangeProfileでhapで有効なプロシージャの確認 (must)
  * [x] hapで有効なプロシージャのみコールするようにする対応 (should+)
* [x] syncXXX系のメソッドがサーバー側に不足しているものについて追加作業を行う。(must)
  * [ ] syncHostParentsについてはひとまずpendingとする。
* [ ] updateType=ALL時の動作 (must)
  * [x] hosts
  * [x] hostGroups
  * [x] hostGroupMembership
  * [x] triggers
  * [ ] hostParents
  * [ ] updateType=ALLの時のhostsのバリデーション結果をレスポンスのJSONのステータスへ反映
  * [x] updateType=ALLの時に変更のあった箇所も反映するように修正[Host, Hostgroup, Trigger]
* [x] getLastInfo実装 (must)
  * queryにserverIdの条件を追加
  * テスト修正
* [x] AMQPでの通信処理 (must)
  * [x] テスト追加
  * [x] 動作検証
  * [x] テストの動かし方をドキュメントに追加
* [ ] fetch系処理用のconnection (may)
    * マルチスレッド処理の簡略化のため現状ではコールのたびにコネクションを張り直しているが、スレッド毎に一つにしたい
* [x] EVENT_TYPE_NOTIFICATIONの追加 (must)
  * [ ] 付随してtrigger statusにも同様のものが必要ではないか? 
* [x] fetch系プロシージャの実装 (must)
  * [x] item
  * [x] history
  * [x] tirgger
* [x] fetchItems/fetchTriggersの修正(HAPI2側のみ) (should)
  * 現在の実装に引数は無いが、HAPI2.0ではhostIdsが追加されている
* [x] fetchEventの実装 (may)
  * 他のfetch系は既に実装があるが、fetchEventの実装は無い
* [ ] プラグイン側methodコール時のタイムアウト処理
* [x] パラメータのvalidate (must)
  * Mandatoryのパラメータが無い場合はInvalid paramsのエラーを返す
* [x] ログ出力の吟味 (must)
* [x] procedureのディスパッチ処理の整理 (must)
* [x] DataStoreFactoryでの起動処理実装 (must)
* [x] ~~HatoholArmPluginGateHAPI2をGUIで登録できるようにする (must)~~
  * ~~server-type-hapi2.sqlを追加する~~ これはプラグイン実装者の仕事
* [x] UI(JavaScript)プラグインの仕組み (must)
  * バックエンドの実装に従って表示する情報やリンク先等を変更
* [ ] セルフモニタリングトリガーの実装
* [x] HAPI2.0用プラグイン起動および終了処理 (must)
  * HAPI1.0ほど頑張らない。起動コマンドおよび終了コマンドのカラムを追加して、
    コマンドが存在すればそれを叩くだけとする。
* [ ] サーバ設定更新のnotification
  * ~~仕様決める必要あり https://github.com/project-hatohol/HAPI-2.0-Specification/issues/23~~ https://github.com/project-hatohol/HAPI-2.0-Specification/issues/23#issuecomment-111004718
* [ ] プラグイン登録の仕組みを整理 (must)
  * [ ] server-types.sqlの提供方法を提示する
  * [ ] UIプラグインの提供方法を提示する
* [ ] TravisCI上でのRabbitMQのテスト(Ubuntu 12.04用のパッケージが無い)
* [ ] 通信処理の抽象化
  * pipe版の追加
* [ ] C++用プラグインSDK・サンプルプラグイン実装

**Comment by ashie** [comment]
5月末段階の目標

* fetch系を除くprocedureが一通り動く状態に
* serversとarm_pluginsにプラグイン情報を入れておけばHatoholArmPluginGateHAPI2が立ち上がるようにする
  * DB直接いじるのは面倒なので、とりあえずのserver-types-hapi2.sqlも入れておく?

**Comment by ashie** [comment]
> HatoholArmPluginGateHAPI2をGUIで登録できるようにする (must)
>    server-type-hapi2.sqlを追加する

設定項目自体はHAPI JSONと同じで良いはず
ただし、実際に使ってみると以下の配慮が必要に感じた

* [ ] 接続ユーザー名やパスワードもブローカーURLに含め（られ）ることを明示した方が良い
* [ ] TLS関連設定はTLSを有効化したときみ表示された方が良い

いずれもserver-typesの仕組みそのものの拡張が必要?

**Comment by ashie** [comment]
> 5月末段階の目標
> 
>     * fetch系を除くprocedureが一通り動き、AMQPで通信できる状態
>         * updateType=ALL系の動作とかは間に合わないかも
>     * serversとarm_pluginsにプラグイン情報を入れておけばHatoholArmPluginGateHAPI2が立ち上がるように
>         * DB直接いじるのは面倒なので、とりあえずのserver-types-hapi2.sqlも入れておく?

これを書いた後に直後に割り込み作業が入ってしまったので、RabbitMQとの接続までは確認が
出来ているが、通信の検証は全然間に合わなかった。仕切り直し。

**Comment by ashie** [comment]
> 設定項目自体はHAPI JSONと同じで良いはず

いや、ZabbixならZabbixの接続情報が必要。
よく考えたら個々のserver-types.sqlはプラグイン実装者の仕事で、サーバ側の仕事じゃなかった。

**Comment by ashie** [comment]
普段の開発環境で、突然 testHatoholArmPluginGateHAPI2::testCommunication の多くのテストで
HatoholArmPluginGateHAPI2が最初のメッセージを取りこぼして失敗するという問題が発生した。
(2個目以降のメッセージは受け取っている)

原因がよく分からず、RabbitMQサーバを再起動すると問題が発生しなくなってしまった。
RabbitMQ側にも特に怪しいログは残っていない。

librabbitmq-cライブラリの使い方等に何か問題があるかもしれない。

**Comment by ashie** [comment]
> * [x] ~~HatoholArmPluginGateHAPI2をGUIで登録できるようにする (must)~~
>   * ~~server-type-hapi2.sqlを追加する~~ これはプラグイン実装者の仕事

テスト用に全部のパラメータの入力ができるserver-type.sqlがあると良さそう。

**Comment by ashie** [comment]
hatohol-server-type-utilに追加するならこんな感じ

```diff
diff --git a/server/tools/hatohol-server-type-util b/server/tools/hatohol-server-type-util
index 67a1605..682b89c 100755
--- a/server/tools/hatohol-server-type-util
+++ b/server/tools/hatohol-server-type-util
@@ -248,6 +248,32 @@ class HapiCeilometerGenerator(ParamGenerator):
         return self.get_sql_version_number()
 
 
+class Hapi2DevParamGenerator(ParamGenerator):
+    def get_server_type(self):
+        return 7 # MONITORING_SYSTEM_HAPI2
+
+    def get_server_type_name(self):
+        return 'HAPI2 [for development]'
+
+    def get_parameters(self):
+        obj = self.get_zabbix_params()
+        obj.append({'id': 'dbName',
+                    'label': 'DB name'})
+        obj.append({'id': 'extendedInfo',
+                    'label': 'extendedInfo'})
+        obj.extend(self.get_hapi_params())
+        return obj
+
+    def get_plugin_path(self):
+        return ''
+
+    def get_sql_file_type_name(self):
+        return 'hapi2-dev'
+
+    def get_sql_version(self):
+        return self.get_sql_version_number()
+
+
 def generate_one_type(table_name, server_type, server_label, parameters,
                       plugin_path, sql_version, file_identifier, uuid):
     PLUGIN_ENABLED = 1
@@ -301,6 +327,7 @@ def main():
         HapiZabbixParamGenerator(),
         HapiJSONParamGenerator(),
         HapiCeilometerGenerator(),
+        Hapi2DevParamGenerator(),
     )
 
     command_handlers = {
```

出来上がるSQL:

server-type-hapi2-dev.sql
```
INSERT INTO server_types (type, name, parameters, plugin_path, plugin_sql_version, plugin_enabled, uuid) VALUES (7, 'HAPI2 [for development]', '[{"id": "nickname", "label": "Nickname"}, {"id": "hostName", "label": "Host name"}, {"id": "ipAddress", "label": "IP address"}, {"default": "80", "id": "port", "label": "Port"}, {"id": "userName", "label": "User name"}, {"inputStyle": "password", "id": "password", "label": "Password"}, {"default": "30", "id": "pollingInterval", "label": "Polling interval (sec)"}, {"default": "10", "id": "retryInterval", "label": "Retry interval (sec)"}, {"id": "dbName", "label": "DB name"}, {"id": "extendedInfo", "label": "extendedInfo"}, {"inputStyle": "checkBox", "id": "passiveMode", "label": "Passive mode"}, {"hint": "(empty: Default)", "allowEmpty": true, "id": "brokerUrl", "label": "Broker URL"}, {"hint": "(empty: Default)", "allowEmpty": true, "id": "staticQueueAddress", "label": "Static queue address"}]', '', 1, 1, '') ON DUPLICATE KEY UPDATE name='HAPI2 [for development]', parameters='[{"id": "nickname", "label": "Nickname"}, {"id": "hostName", "label": "Host name"}, {"id": "ipAddress", "label": "IP address"}, {"default": "80", "id": "port", "label": "Port"}, {"id": "userName", "label": "User name"}, {"inputStyle": "password", "id": "password", "label": "Password"}, {"default": "30", "id": "pollingInterval", "label": "Polling interval (sec)"}, {"default": "10", "id": "retryInterval", "label": "Retry interval (sec)"}, {"id": "dbName", "label": "DB name"}, {"id": "extendedInfo", "label": "extendedInfo"}, {"inputStyle": "checkBox", "id": "passiveMode", "label": "Passive mode"}, {"hint": "(empty: Default)", "allowEmpty": true, "id": "brokerUrl", "label": "Broker URL"}, {"hint": "(empty: Default)", "allowEmpty": true, "id": "staticQueueAddress", "label": "Static queue address"}]', plugin_path='', plugin_sql_version='1', plugin_enabled='1', uuid='';
```

**Comment by ashie** [comment]
> 出来上がるSQL:
> 
> server-type-hapi2-dev.sql

使ってみたら、Broker URLと静的キューアドレスが保存されない。
なんで?

**Comment by ashie** [comment]
あとUUIDも必要か

**Comment by ashie** [comment]
TLS関係も足りなかったので以下の様にしてみた。

```diff
diff --git a/server/tools/hatohol-server-type-util b/server/tools/hatohol-server-type-util
index 67a1605..b7de364 100755
--- a/server/tools/hatohol-server-type-util
+++ b/server/tools/hatohol-server-type-util
@@ -56,6 +56,11 @@ class ParamGenerator:
         obj.append({'id': 'passiveMode',
                     'label': 'Passive mode',
                     'inputStyle': 'checkBox'})
+        obj.extend(self.get_base_amqp_params())
+        return obj
+
+    def get_base_amqp_params(self):
+        obj = []
         obj.append({'id': 'brokerUrl',
                     'label': 'Broker URL',
                     'allowEmpty': True,
@@ -66,6 +71,23 @@ class ParamGenerator:
                     'hint': '(empty: Default)'})
         return obj
 
+    def get_tls_amqp_params(self):
+        obj = []
+        obj.append({'id': 'tlsCertificatePath',
+                    'label': 'TLS client certificate path',
+                    'allowEmpty': True})
+        obj.append({'id': 'tlsKeyPath',
+                    'label': 'TLS client key path',
+                    'allowEmpty': True})
+        obj.append({'id': 'tlsCACertificatePath',
+                    'label': 'TLS CA certificate path',
+                    'allowEmpty': True})
+        obj.append({'id': 'tlsEnableVerify',
+                    'label': 'TLS: Enable verify',
+                    'inputStyle': 'checkBox',
+                    'allowEmpty': True})
+        return obj
+
     def get_sql_file_type_name(self):
         return ''
 
@@ -170,27 +192,8 @@ class HapiJSONParamGenerator(ParamGenerator):
         obj = []
         obj.append({'id': 'nickname',
                     'label': 'Nickname'})
-        obj.append({'id': 'brokerUrl',
-                    'label': 'Broker URL',
-                    'allowEmpty': True,
-                    'hint': '(empty: Default)'})
-        obj.append({'id': 'staticQueueAddress',
-                    'label': 'Static queue address',
-                    'allowEmpty': True,
-                    'hint': '(empty: Default)'})
-        obj.append({'id': 'tlsCertificatePath',
-                    'label': 'TLS client certificate path',
-                    'allowEmpty': True})
-        obj.append({'id': 'tlsKeyPath',
-                    'label': 'TLS client key path',
-                    'allowEmpty': True})
-        obj.append({'id': 'tlsCACertificatePath',
-                    'label': 'TLS CA certificate path',
-                    'allowEmpty': True})
-        obj.append({'id': 'tlsEnableVerify',
-                    'label': 'TLS: Enable verify',
-                    'inputStyle': 'checkBox',
-                    'allowEmpty': True})
+        obj.extend(self.get_base_amqp_params())
+        obj.extend(self.get_tls_amqp_params())
         return obj
 
     def get_sql_file_type_name(self):
@@ -248,6 +251,37 @@ class HapiCeilometerGenerator(ParamGenerator):
         return self.get_sql_version_number()
 
 
+class Hapi2DevParamGenerator(ParamGenerator):
+    def get_server_type(self):
+        return 7 # MONITORING_SYSTEM_HAPI2
+
+    def get_server_type_name(self):
+        return 'HAPI2 [for development]'
+
+    def get_parameters(self):
+        obj = self.get_zabbix_params()
+        obj.append({'id': 'dbName',
+                    'allowEmpty': True,
+                    'label': 'DB name'})
+        obj.append({'id': 'extendedInfo',
+                    'allowEmpty': True,
+                    'label': 'extendedInfo'})
+        obj.extend(self.get_hapi_params())
+        obj.extend(self.get_tls_amqp_params())
+        obj.append({'id': 'uuid',
+                    'label': 'UUID'})
+        return obj
+
+    def get_plugin_path(self):
+        return ''
+
+    def get_sql_file_type_name(self):
+        return 'hapi2-dev'
+
+    def get_sql_version(self):
+        return self.get_sql_version_number()
+
+
 def generate_one_type(table_name, server_type, server_label, parameters,
                       plugin_path, sql_version, file_identifier, uuid):
     PLUGIN_ENABLED = 1
@@ -301,6 +335,7 @@ def main():
         HapiZabbixParamGenerator(),
         HapiJSONParamGenerator(),
         HapiCeilometerGenerator(),
+        Hapi2DevParamGenerator(),
     )
 
     command_handlers = {
```

生成されるSQL:

server-type-hapi2-dev.sql:
```sql
INSERT INTO server_types (type, name, parameters, plugin_path, plugin_sql_version, plugin_enabled, uuid) VALUES (7, 'HAPI2 [for development]', '[{"id": "nickname", "label": "Nickname"}, {"id": "hostName", "label": "Host name"}, {"id": "ipAddress", "label": "IP address"}, {"default": "80", "id": "port", "label": "Port"}, {"id": "userName", "label": "User name"}, {"inputStyle": "password", "id": "password", "label": "Password"}, {"default": "30", "id": "pollingInterval", "label": "Polling interval (sec)"}, {"default": "10", "id": "retryInterval", "label": "Retry interval (sec)"}, {"allowEmpty": true, "id": "dbName", "label": "DB name"}, {"allowEmpty": true, "id": "extendedInfo", "label": "extendedInfo"}, {"inputStyle": "checkBox", "id": "passiveMode", "label": "Passive mode"}, {"hint": "(empty: Default)", "allowEmpty": true, "id": "brokerUrl", "label": "Broker URL"}, {"hint": "(empty: Default)", "allowEmpty": true, "id": "staticQueueAddress", "label": "Static queue address"}, {"allowEmpty": true, "id": "tlsCertificatePath", "label": "TLS client certificate path"}, {"allowEmpty": true, "id": "tlsKeyPath", "label": "TLS client key path"}, {"allowEmpty": true, "id": "tlsCACertificatePath", "label": "TLS CA certificate path"}, {"inputStyle": "checkBox", "allowEmpty": true, "id": "tlsEnableVerify", "label": "TLS: Enable verify"}, {"id": "uuid", "label": "UUID"}]', '', 1, 1, '') ON DUPLICATE KEY UPDATE name='HAPI2 [for development]', parameters='[{"id": "nickname", "label": "Nickname"}, {"id": "hostName", "label": "Host name"}, {"id": "ipAddress", "label": "IP address"}, {"default": "80", "id": "port", "label": "Port"}, {"id": "userName", "label": "User name"}, {"inputStyle": "password", "id": "password", "label": "Password"}, {"default": "30", "id": "pollingInterval", "label": "Polling interval (sec)"}, {"default": "10", "id": "retryInterval", "label": "Retry interval (sec)"}, {"allowEmpty": true, "id": "dbName", "label": "DB name"}, {"allowEmpty": true, "id": "extendedInfo", "label": "extendedInfo"}, {"inputStyle": "checkBox", "id": "passiveMode", "label": "Passive mode"}, {"hint": "(empty: Default)", "allowEmpty": true, "id": "brokerUrl", "label": "Broker URL"}, {"hint": "(empty: Default)", "allowEmpty": true, "id": "staticQueueAddress", "label": "Static queue address"}, {"allowEmpty": true, "id": "tlsCertificatePath", "label": "TLS client certificate path"}, {"allowEmpty": true, "id": "tlsKeyPath", "label": "TLS client key path"}, {"allowEmpty": true, "id": "tlsCACertificatePath", "label": "TLS CA certificate path"}, {"inputStyle": "checkBox", "allowEmpty": true, "id": "tlsEnableVerify", "label": "TLS: Enable verify"}, {"id": "uuid", "label": "UUID"}]', plugin_path='', plugin_sql_version='1', plugin_enabled='1', uuid='';
```

> 使ってみたら、Broker URLと静的キューアドレスが保存されない。
> なんで?

サーバ側の修正が足りなかったので、修正した。
これでGUIで全部の値を入れられて、HatoholArmPluginGateHAPI2を起動できる。

**Comment by ashie** [comment]
>  UI(JavaScript)プラグインの仕組み (must)

以下のブランチで、現状の監視サーバ依存の実装を/static/js.plugins以下に切り出してみた

https://github.com/project-hatohol/hatohol/tree/ui-plugin

* ファイル名は何でも良い(/static/js.plugins/*.jsは全て読み込まれる)が、他のプラグインとバッティングしないように"プラグインのUUID.js"にしておくのが良いと思う
  * 組み込みのものやHAPI1のプラグインについてはヒューマンリーダブルな名前にした
* 各プラグインは hatohol.hap_UUID オブジェクトに必要なものを実装する。現状必要なものは以下(あくまでも現在の実装を切り出しただけのもの)
  * label (文字列)
  * getTopURL()
  * getItemGraphURL()
  * getMapsURL()
* 組み込みのものおよびHAPI1のプラグインについては、UUIDの代わりに組み込みのtype値(0〜6)を仕様する
* もう少しプラグイン毎に柔軟にレンダリングできるAPIを定義したいが、他にやるべきTODOがまだまだ残っているので、今回はこの程度にしておく。

**Comment by ashie** [comment]
JavaScriptファイルの読み込み方法はいくつか考えられるが、ひとまずDjangoでやることにした。

**Comment by ashie** [comment]
> HAPI1.0ほど頑張らない。起動コマンドおよび終了コマンドのカラムを追加して、 コマンドが存在すればそれを叩くだけとする。

これは現在のArmPluginInfoのpathをそのまま使えば良いか? (start/stopは引数で制御)

**Comment by ashie** [comment]
> これでGUIで全部の値を入れられて、HatoholArmPluginGateHAPI2を起動できる。

baseUrlが抜けていた。
あと、WebUIで既存の監視サーバ設定を編集するとき、監視サーバタイプの対応付けが
ちゃんとできていない気がする。

**Comment by ashie** [comment]
>> UI(JavaScript)プラグインの仕組み (must)
> 以下のブランチで、現状の監視サーバ依存の実装を/static/js.plugins以下に切り出してみた

せめてserverInfoのextendedInfoを扱う仕組みを追加しないと使い物にならない気がする。

**Comment by ashie** [comment]
> UI(JavaScript)プラグインの仕組み (must)

これを導入したら、今のserver-typesは不要な気がしてきた。
たぶん無くしてしまった方がすっきりする。
15.06(15.07?)には間に合わないが。

**Comment by ashie** [comment]
> これを導入したら、今のserver-typesは不要な気がしてきた。
> たぶん無くしてしまった方がすっきりする。

サーバ側でvalidationしたいのでそうもいかないか?

**Comment by ashie** [comment]
> * HAPI2.0用プラグイン起動および終了処理 (must)
>    * HAPI1.0ほど頑張らない。起動コマンドおよび終了コマンドのカラムを追加して、 コマンドが存在すればそれを叩くだけとする。

リアルミーティングではユーザーメイドの起動スクリプトを設置できるようにし、それをメニューで選択
できるようにするとよいのではという案も出ていたが、今回は実装できなかった。
今後そういったニーズが出てきたら改めて検討する。

**Comment by ashie** [comment]
> * 接続ユーザー名やパスワードもブローカーURLに含め（られ）ることを明示した方が良い

> いずれもserver-typesの仕組みそのものの拡張が必要?

欄外かバルーンヘルプか何かでもう少し詳しい説明を入れることを想定していたが、
今のところplaceholderでURL形式を示すだけに止めた。

**Comment by ashie** [comment]
> 普段の開発環境で、突然 testHatoholArmPluginGateHAPI2::testCommunication の多くのテストで
> HatoholArmPluginGateHAPI2が最初のメッセージを取りこぼして失敗するという問題が発生した。

色々修正しているうちに発生しなくなった。

**Comment by ashie** [comment]
残りのTODOは別issueにした後、本issueは閉じる。

**Comment by ashie** [comment]
> 各プラグインは hatohol.hap_UUID オブジェクトに必要なものを実装する。現状必要なものは以下(あくまでも現在の実装を切り出しただけのもの)

本当に切り出しただけなので、仕様が酷い。
URL取得用の関数はエスケープするのではなくて生のURLをreturnすべき。

**Comment by ashie** [comment]
> セルフモニタリングトリガーの実装

#1448 に切り出した。

**Comment by ashie** [comment]
>  syncHostParentsについてはひとまずpendingとする。

> hostParents

まとめて #1454

**Comment by ashie** [comment]
> サーバ設定更新のnotification 

#1455

**Comment by ashie** [comment]
> プラグイン側methodコール時のタイムアウト処理

#1458

**Comment by ashie** [comment]
> fetch系処理用のconnection (may)
>    マルチスレッド処理の簡略化のため現状ではコールのたびにコネクションを張り直しているが、スレッド毎に一つにしたい

fetch系APIについてはもともと短時間に何度も投げるべきではないAPIなので、今の実装でも大きな
問題とはならないと思われる。問題になるようであれば改めてissueを立てる。

**Comment by ashie** [comment]
> 付随してtrigger statusにも同様のものが必要ではないか? 

これも問題があれば改めてissueを立てる

**Comment by ashie** [comment]
> プラグイン登録の仕組みを整理 (must) 

#1459

**Comment by ashie** [comment]
> TravisCI上でのRabbitMQのテスト(Ubuntu 12.04用のパッケージが無い)

#1460

**Comment by ashie** [comment]
> 通信処理の抽象化
>     pipe版の追加

> C++用プラグインSDK・サンプルプラグイン実装

この辺りは必要性が見えてきたときにissueを立てる。
